### ISSUE TITLE
New charting specs

### ISSUE THREAD

**Issue by dxinteractive** [bigdatr/bd-peanut#12]
Some examples to get your mind limber:
https://docs.google.com/spreadsheets/d/1mDViacD51PPNYiwZKCY5xavfKao7OxaLu2j_ZljsGvM/edit?usp=sharing

# Proposed chart data stucture

To be turned into an Immutable record. Example:

```
{
	// provides knowledge of keys, associated labels, and implied order
	// if data values are numbers, this data is continuous, if not then its discrete

	columns: [
		{
			key: 'day',
			label: 'Day'
		{
			key: 'supply',
			label: 'Supply (houses)'
		},
		{
			key: 'demand',
			label: 'Demand (houses)'
		},
		{
			key: 'fruit',
			label: 'Random fruit'
		}
	],
	data: [
		{
			day: 1,
			supply: 34,
			demand: 99,
			fruit: "apple"
		},
		{
			day: 2,
			supply: 32,
			demand: 88,
			fruit: "apple"
		},
		{
			day: 3,
			supply: 13,
			demand: 55,
			fruit: "orange"
		},
		{
			day: 8,
			supply: 22,
			demand: 56,
			fruit: "peach"
		},
		{
			day: 19
			supply:  12
			demand:  4,
			fruit: "pear"
		}
	]
}
```
# Possible methods
```
min(key) // returns minimum value of `key` in collection
max(key) // returns minimum value of `key` in collection
sum(key) // returns sum of values of `key` in collection
isContinuous(key) // returns true if the data is continuous.
// which can be determined by checking if the value of the given on the first valid non-null item in the data collection is a Number, where a valid item is a number, string or null. If false, the data is discrete
```

Methods that return the data point with the max or min of a value (as opposed to the max or min value) are not yet scoped, as the result may be more than one data point.

The idea of 'primary' columns / dimensions should not be reflected in the data structure,
its up to the charts to find out which column to use as primary based on their props.

# Charts and Props

All charts will accept `data`, a chartdata object.

## Line / area
  - `data`
  - `x: string` (primary column)
  - `y: string|string[]` or `lines: string|string[]` (value columns)
  - Plane props

## Scatter / Bubble 

(has no primary column as such,  just has a point on the chart for every data point)
  - `data`
  - `x: string` (value column)
  - `y: string` (value column)
  - `size: string` (value column)
  - `color: string` (value column)
  - Plane props

## Column
  - `data`
  - `x` (primary column)
  - `y: string|string[]` or `columns: string|string[]` (value columns)
  - Plane props

## Bar
  - `data`
  - `y` (primary column)
  - `x: string|string[] or bars: string|string[]` (value columns)
  - Plane props

## Pie / Strudel / Doughnut
  - `data`
  - `slices: string` (primary column)
  - `size: string` (value column)

# "Plane"

Kinf of hocky thing that knows about the concept of a plane. Displays two spatial axis. Both axis are treated as continuous, and work best when given continuous data for both domain and range. 

- If non-continuous data is provided to the primary axis (the domain, usually the x axis then it must treat these as equally spaced. Think of a line chart with "red", "green", "blue" along its x axis. This situation usually means you should probably be using a bar chart, but it can happen.
- If non-continuous data is provided to the secondary axis (the range, usually the y axis) then the charts behaviour is undefined. This is like trying to chart the colour of someones shirt over time using a line chart, it doesn't make any sense.

### Abilities and commonalities
- They may have grid lines and/or ticks on the domain and/or the range of the chart.
- They may have the potential ability to zoom on the domain and/or the range?
- Can have arbitrary shapes drawn on the plane, like a vertical line or benchmark line.
- Scales? Like exp, log, sqrt etc.

### Plane props

Automatically calculate these from the data when not explicitly passed in.

- `rangeMin`
- `rangeMax`
- `domainMin`
- `domainMax`

e.g. the values in the data that would place a point on any edge of the chart.

### Special case Plane with only 1 continuous dimensions, like Bar and Column charts!

Displays a range, but there is no actual domain as the data on that axis is treated as discrete. It's ideal for displaying non-continuous data on the primary axis, and continuous data on the secondary axis.

- If continuous data is provided to the primary axis (domain) then it must treat these as ordered and discrete. Pretty much just use integers (0, 1, 2, 3). The chart will have to pass numbers down to its renderer anyway, so you'll probably just need to use array indexes for positioning in all cases, and set the `minDomain` and `maxDomain` accordingly.

- If non-continuous data is provided to the secondary (range) axis then the charts behaviour is undefined. This is like someone trying to chart "green" number of hats. It's dumb.

### Warning!

Bar and column charts will render the same data set horizontally or vertically! This means that the x and y coords in the data could end up being vertical or horizontal after rendering.

### Abilities and commonalities
- They may have grid lines and/or ticks on the range of the chart.
- They may have the potential ability to zoom on the range?

## Desserts

Pies, strudels and doughnuts do not display on a plane.

- If continuous data is provided to the primary axis (the column that contains the 'slices') then it must treat these as discrete (just use toString()).
- If discrete data is provided to the secondary (range) axis then the charts behaviour is undefined.
- These can only show one non-primary value at a time.

# Example component hierarchy

```
<Line>
    Plane2D( // and / or Animation() or other hocky stuff
        <Chart>
            <LineCanvas />
            <AxisX />
            <AxisY />
        </Chart>
    )
</Line>
```

**Comment by dxinteractive** [comment]
We'll need to decide on Option 1 or 2 for the chart data structure. I'm thinking that option 1 is more extensible.

**Comment by dancoates** [comment]
Yeah I definitely prefer option 1

**Comment by allanhortle** [comment]
Issue moved to [bigdatr/pnut #12](https://github.com/bigdatr/pnut/issues/12) via [**ZenHub**](https://www.zenhub.com/)
