### ISSUE TITLE
Animation discussion

### ISSUE THREAD

**Issue by dxinteractive** [bigdatr/bd-peanut#13]
### SVG animation / CSS transitions
- Generally more smooth and render performant
- Easier to implement
- Without care they can tween data points to other unrelated data points. Data points need to be uniquely identifiable by the animator to tween correctly, and if that can be achieved then the tweens will look correct. Windowed pans through data should not be confused with interpolation of value changes.
- Can't be used as-is to render a static representation of the transition or interpolated states (such as onion skins, or viewing the "4.5th" data point etc.) as the easing is outside of the component. Can be overcome with algorithm duplication.
- Can't cope with dynamically changing transition speeds, such as scrubbing the playhead
- Depending on the method used, make sure that animations can immediately override each other without jumping

### Javascript / component based interpolation and re-rendering
- Potentially a lot less render performant unless care is taken
- Tweening data points *correctly* is easier as the animator can more easily receive data about which point is which by using some kind of unique id. There still exists the problem of ensuring there is rich enough data to be able to uniquely identify data points in the first place, and to cope with the transition to when those points no longer exist, hereby known as the "disappearing data point" problem.
- More control over tween algorithms (i.e. can do any kind of interpolation, including all from D3, and even non-keyframe based interpolations like exponential moving averages if we want)
- Ability to render a static representation of the transition and interpolated states (such as onion skins, or viewing the "4.5th" data point etc.) as the easing and playhead position is known to the component.
- Can cope with dynamically changing transition speeds, such as scrubbing the playhead

## The "disappearing data point" problem
- Data in a data set that has info over time must be rich enough to be able to uniquely identify every data point, so that they can be interpolated correctly. Using the position of each data point in the array is not a valid method as data points may pop in and out of existence. Reason for that  happening:
   1. The data set may omitting values that don't exist
   2.  The view applying windowing / panning / zooming
- Given this, there is still the issue of how to "tween away" data points that disappear over time. Where do they go and how do they animate there? Or do they just disappear?
   1. Possibly can have the class for data-over-time analyze the data set and zero-fill missing values
   2. This can be compensated for in the component, as it'll have knowledge of view limits and can therefore has the data required to calculate which data point is which, *if* the data set is rich enough.
- ... more to come

**Comment by allanhortle** [comment]
Issue moved to [bigdatr/pnut #13](https://github.com/bigdatr/pnut/issues/13) via [**ZenHub**](https://www.zenhub.com/)
